---
kind: pipeline
name: release

trigger:
  ref:
  - refs/tags/v*
  event:
    exclude:
    - promote

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}

steps:
- name: publish docker
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  environment:
    REGISTRY_USER:
      from_secret: REGISTRY_USER
    REGISTRY_TOKEN:
      from_secret: REGISTRY_TOKEN
  commands:
  - export CONTAINER_NAME=registry.gitlab.com/${DRONE_REPO}:${DRONE_TAG##v}
  - sleep 5 # give docker enough time to start
  - docker login -u $${REGISTRY_USER} -p $${REGISTRY_TOKEN} registry.gitlab.com
  - docker build -t $${CONTAINER_NAME} .
  - docker push $${CONTAINER_NAME}

---
kind: pipeline
type: exec
name: deploy

trigger:
  event:
  - promote
  target:
  - production

node:
  env: prod
  scope: deploy
  domain: abbex.kz

steps:
- name: deploy to production
  environment:
    REGISTRY_USER:
      from_secret: REGISTRY_USER
    REGISTRY_TOKEN:
      from_secret: REGISTRY_TOKEN
    DIRECTUS_URL:
      from_secret: DIRECTUS_URL
    SENTRY_DSN:
      from_secret: SENTRY_DSN
  commands:
  - export CONTAINER_NAME=registry.gitlab.com/${DRONE_REPO}:${DRONE_TAG##v}
  - docker login -u $${REGISTRY_USER} -p $${REGISTRY_TOKEN} registry.gitlab.com
  - docker pull $${CONTAINER_NAME}
  - docker stack deploy -c service.yml --with-registry-auth www
