version: "3"

networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  traefik-public:
    external: true

services:
  dpksklad-kz:
    image: ${CI_CONTAINER_NAME?Variable not set}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public

        - traefik.http.routers.dpksklad-kz-http.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.dpksklad-kz-http.entrypoints=http
        - traefik.http.routers.dpksklad-kz-http.middlewares=https-redirect

        - traefik.http.routers.dpksklad-kz-https.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.dpksklad-kz-https.entrypoints=https

        - traefik.http.routers.dpksklad-kz-https.tls=true
        - traefik.http.routers.dpksklad-kz-https.tls.certresolver=acme_resolver

        - traefik.http.services.dpksklad-kz.loadbalancer.server.port=3000
    networks:
      # use the public network created to be shared between traefik and
      # any other service that needs to be publicly available with https
      - traefik-public
