import { createContext } from 'react';
export const MobileMenuContext = createContext(null);
export const ModalCityContext = createContext(null);
export const ModalBasketContext = createContext(null);
export const BasketArrContext = createContext(null);
export const ModalInstructionContext = createContext(null);
export const ModalInstructionVidContext = createContext(null);
export const ModalDataSentContext = createContext(null);
export const ModalFormContext = createContext(null);
export const ModalPartnershipContext = createContext(null);
export const ModalFormPartnersFullContext = createContext(null);
export const ModalQuizContext = createContext(null);